apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-vault-deployment-example
  annotations:
    avp.kubernetes.io/path: "dog-kv-v2/data/credentials"
  labels:
    app: argocd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-demo
  template:
    metadata:
      labels:
        app: argocd-demo
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        env:
        - name: USERNAME
          value: <user>
        - name: PASSWORD
          value: <password>
        envFrom:
        - secretRef:
            name: argocd-vault-dynamic-secret-example