kind: Secret
apiVersion: v1
metadata:
  name: secret-demo
type: Opaque
stringData:
  USERNAME: <path:content-kv-v2/data/db-credentials#user>
  PASSWORD: <path:content-kv-v2/data/db-credentials#password>