kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
stringData:
  AVP_AUTH_TYPE: "approle"
  AVP_ROLE_ID: "42e18c47-5e47-82b5-b102-0e2a11107165"
  AVP_SECRET_ID: "d4199469-826a-c24e-7351-2f214deccb71"
  AVP_TYPE: "vault"
  VAULT_ADDR: "http://10.99.245.73:8200"