apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-env-demo
  annotations:
    avp.kubernetes.io/path: "dog-kv-v2/data/credentials"
  labels:
    app: deployment-env-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-env-demo
  template:
    metadata:
      labels:
        app: deployment-env-demo
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        env:
        - name: USERNAME
          value: <user>
        - name: PASSWORD
          value: <password>